name: Setup Node.js environment
description: Setup a Node.js environment with secure feed.
inputs:
  node-version:
    description: Node version
    required: true
    default: lts/Hydrogen
  secure-feed:
    description: Use secure feed (required for production)
    required: true
    default: true
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        cache: npm
        node-version: ${{ inputs.node-version }}
    - if: ${{ inputs.secure-feed }}
      name: Set up secure feed
      run: npx https://aka.ms/EnableSecureFeed
      shell: bash
