name: Print step summary from file
description: Print step summary from file
inputs:
  path:
    required: true
  title: {}
  type: {}
runs:
  using: composite
  steps:
    - run: |
        echo \<details\>\<summary\>${{ inputs.title || format('Content of {0}', inputs.path) }}\</code\>\</summary\> >> $GITHUB_STEP_SUMMARY
        echo >> $GITHUB_STEP_SUMMARY
        echo \`\`\`${{ inputs.type }} >> $GITHUB_STEP_SUMMARY
        cat ${{ inputs.path }} >> $GITHUB_STEP_SUMMARY && true || exit 1
        echo \`\`\` >> $GITHUB_STEP_SUMMARY
        echo \</details\> >> $GITHUB_STEP_SUMMARY
      shell: bash
