name: Bump version
description: Bump version of a workspace package and its depending workspace packages
inputs:
  name:
    description: Name of the package
    required: true
  version:
    description: Version
    required: true
outputs:
  version:
    value: ${{ steps.version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Bump version
      run: npm version --no-git-tag-version --package-lock-only --workspace=${{ inputs.name }} ${{ inputs.version }}
      shell: bash

    - id: path
      uses: ./.github/actions/look-up-package-path
      with:
        name: ${{ inputs.name }}

    - id: version
      name: Print version
      run: echo version=$(cat ${{ steps.path.outputs.path }}/package.json | jq -r '.version') | tee --append $GITHUB_OUTPUT
      shell: bash

    - name: Bump depending workspace packages
      run: |
        for path in `cat package.json | jq -r '.workspaces | join("\n")'`
        do
          name=$(cat $path/package.json | jq -r '.name')

          echo ::group::$name

          cat $path/package.json | jq -r '.dependencies + .devDependencies'

          if [[ "$(cat $path/package.json | jq --arg name "${{ inputs.name }}" -r 'if (.dependencies + .devDependencies)[$name] then true else false end')" == "true" ]]
          then
            # The actual version bumped to, may differ from inputs.version, such as "prepatch".
            # We should bump to what is in the package.json.
            # We should do audit at another time, not when bumping versions.
            npm install --no-audit --package-lock-only --workspace=$name ${{ inputs.name }}@${{ steps.version.outputs.version }}
          fi

          echo ::endgroup::
        done
      shell: bash
