name: Look up package path
description: Look up package path given its package name
inputs:
  name:
    description: Name of the package
    required: true
outputs:
  path:
    value: ${{ steps.look-up-package-path.outputs.path }}

runs:
  using: composite
  steps:
    - name: 'Sanity check: root package.json exists'
      run: compgen -G package.json
      shell: bash
    - name: 'Sanity check: root package.json is a workspace'
      run: cat package.json | jq -r 'if .workspaces | length > 0 then empty else halt_error(1) end'
      shell: bash
    - id: look-up-package-path
      name: Get package path
      run: |
        # We cannot use "npm ls" because this could run before "npm ci".
        for path in `cat package.json | jq -r '.workspaces | join("\n")'`
        do
          if [[ "`cat $path/package.json | jq -r '.name'`" == "${{ inputs.name }}" ]]
          then
            echo Found package "${{ inputs.name }}" at $path/package.json.
            cat $path/package.json

            echo path=$path | tee --append $GITHUB_OUTPUT
            exit 0
          fi
        done

        exit 1
      shell: bash
    - name: 'Sanity check: path contains the specific package'
      run: |
        name=`cat ${{ steps.look-up-package-path.outputs.path }}/package.json | jq -r '.name'`

        if [[ "$name" != "${{ inputs.name }}" ]]
        then
          exit 1
        fi
      shell: bash
