name: Check if a package is already published
description: Check if a package is already published given its name and version
inputs:
  name:
    description: Name of the package
    required: true
  token:
    description: Registry auth token
  version:
    description: Version of the package
    required: true
outputs:
  published:
    value: ${{ steps.check-publish-status.outputs.published }}
runs:
  using: composite
  steps:
    - env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
      id: check-publish-status
      run: |
        npm view ${{ inputs.name }}@{{ inputs.version }} --json 2>/dev/null | tee /tmp/output.json
        PUBLISHED=`cat /tmp/output.json | jq -r 'if .error then if .error.code == "E404" then false else halt_error(1) end else true end'` && true || exit 1

        echo published=$PUBLISHED >> $GITHUB_OUTPUT
      shell: bash
