name: Continuous deployment

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.devcontainer/**'
      - '.github/**'
  workflow_dispatch: {}

jobs:
  build:
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - lts/Hydrogen
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Append commitish to package version
        run: |
          for i in `ls ./packages/ -1`; do
            cd ./packages/$i/
            cat package.json | jq -r .version | xargs -L1 npx semver@latest $1 --increment prerelease -n false --preid `git branch --show-current`.`date +%Y%m%d`.`git log --pretty=format:'%h' -1 .` | xargs -L1 npm version --no-git-tag-version $1
          done
      - name: Generate versions file
        run: |
          echo {} > versions.json
          for i in `ls ./packages/ -1`; do
            cd ./packages/$i/
            cat ./package.versions.json | jq --argfile packageJSON ./packages/$i/package.json -rS '. + { ($packageJSON.name): $packageJSON.version }' > ./versions.json.tmp
            mv ./versions.json.tmp ./versions.json
          done
      - name: Show versions file
        run: cat versions.json
