name: Publish package
run-name: Publish ${{ inputs.package-name }}

on:
  workflow_dispatch:
    inputs:
      # In pull-request-validation.yml, we enforce that the package name must equals to the package path.
      package-name:
        description: Package name
        options:
          - powerva-chat-adapter
          - powerva-turn-based-chat-adapter-framework
        required: true
        type: choice

concurrency: publish-package/${{ inputs.package-name }}

env:
  node-version: lts/Hydrogen
  # TODO: Change this to AzDO
  redirect-registry-url: https://registry.npmjs.org/

jobs:
  build:
    name: Build
    outputs:
      package-path: ${{ steps.get-package-json.outputs.package-path }}
      tarball-path: ${{ steps.pack-tarball.outputs.tarball-path }}
      version: ${{ steps.bump-version.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: ${{ env.node-version }}
          # TODO: Use AzDO Artifacts
          # registry-url: https://registry.npmjs.org/
          # token: ...
      - name: Redirect package-lock.json
        run: |
          cat package-lock.json | jq -r '.packages = (.packages | with_entries(.value = (.value | (if ((.link | not) and .resolved) then (.resolved = "${{ env.redirect-registry-url }}" + (.resolved | ltrimstr("https://registry.npmjs.org/"))) else . end))))' > package-lock.json.tmp
          mv package-lock.json.tmp package-lock.json
      - run: npm clean-install
      - # Gets the path of the package which match inputs.package-name.
        id: get-package-json
        name: Get package JSON
        run: echo package-path=`npm ls --workspace=${{ inputs.package-name }} --json | jq --arg packageName ${{ inputs.package-name }} -r '.dependencies[$packageName].resolved | ltrimstr("file:../") | if . then . else halt_error(1) end'` >> $GITHUB_OUTPUT
      - name: 'Sanity check: found package path'
        run: |
          ls -l ${{ steps.get-package-json.outputs.package-path }}
          compgen -G ${{ steps.get-package-json.outputs.package-path }}/package.json
      - name: 'Sanity check: package.json/name is same as package-name'
        run: |
          cat ${{ steps.get-package-json.outputs.package-path }}/package.json | jq '.name'
          cat ${{ steps.get-package-json.outputs.package-path }}/package.json | jq '.name == "${{ inputs.package-name }}" | if . then empty else halt_error(1) end'
      - name: 'Sanity check: package.json/version must be prerelease'
        run: |
          cat ${{ steps.get-package-json.outputs.package-path }}/package.json | jq '.version'
          cat ${{ steps.get-package-json.outputs.package-path }}/package.json | jq '.version | contains("-") | if . then empty else halt_error(1) end'
      - id: bump-version
        name: Bump version
        run: |
          npm version --no-git-tag-version --workspace=${{ inputs.package-name }} patch
          echo version=`npm version --json --workspace=${{ inputs.package-name }} | jq --arg packageName ${{ inputs.package-name }} -r '.[$packageName]'` >> $GITHUB_OUTPUT
          cat ${{ steps.get-package-json.outputs.package-path }}/package.json
      - name: Build
        run: npm run build --if-present --workspaces=true
      - id: pack-tarball
        name: Pack tarball
        run: |
          npm pack --pack-destination=$PWD --workspace=${{ inputs.package-name }}
          echo tarball-path=${{ inputs.package-name }}-${{ steps.bump-version.outputs.version }}.tgz >> $GITHUB_OUTPUT
      - name: 'Sanity check: got tarball'
        run: compgen -G ${{ steps.pack-tarball.outputs.tarball-path }}
      - name: Upload tarball artifact
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: ${{ steps.pack-tarball.outputs.tarball-path }}

  prepare-to-publish:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download tarball artifact
        uses: actions/download-artifact@v3
        with:
          name: package
      - name: Summary
        run: |
          echo \| Package name \| Version \| >> $GITHUB_STEP_SUMMARY
          echo \| - \| - \| >> $GITHUB_STEP_SUMMARY
          echo \| ${{ inputs.package-name }} \| ${{ needs.build.outputs.version }} \| >> $GITHUB_STEP_SUMMARY
          echo >> $GITHUB_STEP_SUMMARY
          echo \<details\>\<summary\>Content of \<code\>packages/${{ inputs.package-name }}/package.json\</code\>\</summary\> >> $GITHUB_STEP_SUMMARY
          echo >> $GITHUB_STEP_SUMMARY
          echo \`\`\`json >> $GITHUB_STEP_SUMMARY
          tar --extract --file=${{ needs.build.outputs.tarball-path }} --to-stdout package/package.json >> $GITHUB_STEP_SUMMARY
          echo \`\`\` >> $GITHUB_STEP_SUMMARY
          echo \</details\> >> $GITHUB_STEP_SUMMARY
          echo >> $GITHUB_STEP_SUMMARY
          echo \<details\>\<summary\>Content of \<code\>${{ needs.build.outputs.tarball-path }}\</code\>\</summary\> >> $GITHUB_STEP_SUMMARY
          echo >> $GITHUB_STEP_SUMMARY
          echo \`\`\` >> $GITHUB_STEP_SUMMARY
          tar --list --file=${{ needs.build.outputs.tarball-path }} --verbose >> $GITHUB_STEP_SUMMARY
          echo \`\`\` >> $GITHUB_STEP_SUMMARY
          echo \</details\> >> $GITHUB_STEP_SUMMARY

  publish-to-npm:
    environment:
      name: npm-publish
      url: ${{ steps.publish.outputs.url }}
    name: Publish to NPM
    needs:
      - build
      - prepare-to-publish
    runs-on: ubuntu-latest
    steps:
      - name: Download tarball artifact
        uses: actions/download-artifact@v3
        with:
          name: package
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          # TODO: Use AzDO Artifacts
          # registry-url: https://registry.npmjs.org/
          # token: ...
      - # TODO: Add publish to NPM
        id: publish
        name: Publish
        run: |
          echo TODO: npm publish --access public ${{ needs.build.outputs.tarball-path }}

          URL=https://npmjs.com/package/${{ inputs.package-name }}/v/${{ needs.build.outputs.version }}
          echo url=$URL >> $GITHUB_OUTPUT
          echo Published to $URL. >> $GITHUB_STEP_SUMMARY

  create-release:
    environment:
      name: pull-request
      url: ${{ steps.create-release.outputs.url }}
    name: Create tag
    needs:
      - build
      - publish-to-npm
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download tarball artifact
        uses: actions/download-artifact@v3
        with:
          name: package
      - # We need to use "gh api" to create a tag/ref.
        # Otherwise, if last commit was modifying workflow, it will fail with permission issues.
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        id: push-tag
        name: Push tag
        run: |
          TAG=release/${{ inputs.package-name }}/v${{ needs.build.outputs.version }}
          URL=${{ github.server_url }}/${{ github.repository }}/tree/$TAG

          gh api repos/${{ github.repository }}/git/refs --field ref=refs/tags/$TAG --field sha=${{ github.sha }}

          echo tag=$TAG >> $GITHUB_OUTPUT
          echo url=$URL >> $GITHUB_OUTPUT

          echo Tag [\`$TAG\`]\($URL\) created. >> $GITHUB_STEP_SUMMARY
      - env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        id: create-release
        name: Create release
        run: |
          DATE=`date +%F`
          URL=${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ steps.push-tag.outputs.tag }}

          gh release create ${{ steps.push-tag.outputs.tag }} ./*.tgz --repo ${{ github.repository }} --title "${{ inputs.package-name }}@${{ needs.build.outputs.version }} - $DATE"
          echo url=$URL >> $GITHUB_OUTPUT

          echo Release at $URL >> $GITHUB_STEP_SUMMARY

  create-bump-prepatch-pull-request:
    environment:
      name: pull-request
      url: ${{ steps.create-pull-request.outputs.url }}
    name: Create pull request to bump to prepatch
    needs:
      - build
      - publish-to-npm
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: ${{ env.node-version }}
          # TODO: Use AzDO Artifacts
          # registry-url: https://registry.npmjs.org/
          # token: ...
      - env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        id: create-branch
        name: Create branch
        run: |
          BRANCH_NAME=bot/postpublish/${{ inputs.package-name }}/v${{ steps.bump-to-prepatch.outputs.version }}

          git config user.email "${{ format('@{0}', github.actor) }}"
          git config user.name "${{ format('@{0}', github.actor) }}"

          git checkout -b $BRANCH_NAME

          echo branch-name=$BRANCH_NAME >> $GITHUB_OUTPUT
      - name: Bump CHANGELOG.md
        run: |
          npx keep-a-changelog --url="${{ github.server_url }}/${{ github.repository }}" --format=markdownlint --release ${{ needs.build.outputs.version }}
          git add ./CHANGELOG.md
      - id: bump-to-prepatch
        name: Bump to prepatch
        run: |
          VERSION=`npx semver@latest -i prepatch ${{ needs.build.outputs.version }}`
          echo version=$VERSION >> $GITHUB_OUTPUT

          npm version --no-git-tag-version --workspace=${{ inputs.package-name }} $VERSION

          git add ./package-lock.json
          git add ./packages/${{ inputs.package-name }}/package.json

          cat ${{ needs.build.outputs.package-path }}/package.json

          echo Bump [\`${{ inputs.package-name }}\`]\(${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}/packages/${{ inputs.package-name }}/\) to \`$VERSION\`. >> $GITHUB_STEP_SUMMARY
          echo >> $GITHUB_STEP_SUMMARY
          echo \<details\>\<summary\>Content of \<code\>packages/${{ inputs.package-name }}/package.json\</code\>\</summary\> >> $GITHUB_STEP_SUMMARY
          echo >> $GITHUB_STEP_SUMMARY
          echo \`\`\`json >> $GITHUB_STEP_SUMMARY
          cat ./packages/${{ inputs.package-name }}/package.json >> $GITHUB_STEP_SUMMARY
          echo \`\`\` >> $GITHUB_STEP_SUMMARY
          echo \</details\> >> $GITHUB_STEP_SUMMARY
      - env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        name: Commit branch
        run: |
          BRANCH_NAME=${{ steps.create-branch.outputs.branch-name }}

          git commit -m "Bump ${{ inputs.package-name }}@${{ steps.bump-to-prepatch.outputs.version }}"
          git push --set-upstream origin $BRANCH_NAME

          echo Branch created at [\`$BRANCH_NAME\`]\(${{ github.server_url }}/${{ github.repository }}/tree/$BRANCH_NAME\). >> $GITHUB_STEP_SUMMARY
      - env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        id: create-pull-request
        name: Create pull request
        run: |
          URL=`gh pr create --assignee @me --body "Post-publish of ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}." --fill --label bot --repo ${{ github.repository }}`

          echo url=$URL >> $GITHUB_OUTPUT
          echo Pull request created at $URL. >> $GITHUB_STEP_SUMMARY
