name: Publish package

on:
  workflow_dispatch:
    inputs:
      # In pull-request-validation.yml, we enforce that the package name must equals to the package path.
      package-name:
        description: Package name
        options:
          - powerva-turn-based-chat-adapter-framework
          - powerva-chat-adapter
        required: true
        type: choice
      version:
        description: Release version
        options:
          - major
          - minor
          - patch
          - custom
        required: true
        type: choice
      custom-version:
        description: Custom version
        required: false
        type: string

concurrency: publish-package

env:
  node-version: lts/Hydrogen

jobs:
  sanity-check:
    name: Sanity check
    runs-on: ubuntu-latest
    steps:
      - name: 'Sanity check: valid version'
        run: |
          if [ "${{ inputs.version }}" == "custom" ]
          then
            npx semver "${{ inputs.custom-version }}"
          fi

  build:
    env:
      version: ${{ inputs.version == 'custom' && inputs.custom-version || inputs.version }}
    name: Build
    needs:
      - sanity-check
    outputs:
      package-path: ${{ steps.get-package-json.outputs.package-path }}
      version: ${{ steps.bump-version.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: ${{ env.node-version }}
      - run: npm clean-install
      - # Gets the path of the package which match inputs.package-name.
        id: get-package-json
        name: Get package JSON
        run: echo package-path=`npm ls --workspace=${{ inputs.package-name }} --json | jq --arg packageName ${{ inputs.package-name }} -r '.dependencies[$packageName].resolved | ltrimstr("file:../") | if . then . else halt_error(1) end'` >> $GITHUB_OUTPUT
      - name: 'Sanity check: found package path'
        run: |
          ls -l ${{ steps.get-package-json.outputs.package-path }}/package.json
          compgen -G ${{ steps.get-package-json.outputs.package-path }}/package.json
      - name: 'Sanity check: package.json/name is same as package-name'
        run: |
          cat ${{ steps.get-package-json.outputs.package-path }}/package.json
          cat ${{ steps.get-package-json.outputs.package-path }}/package.json | jq '.name == "${{ inputs.package-name }}" | if . then empty else halt_error(1) end'
      - id: bump-version
        name: Bump version
        run: |
          npm version --no-git-tag-version --workspace=${{ inputs.package-name }} ${{ env.version }}
          echo version=`npm version --json --workspace=${{ inputs.package-name }} | jq --arg packageName ${{ inputs.package-name }} -r '.[$packageName]'` >> $GITHUB_OUTPUT
          cat ${{ steps.get-package-json.outputs.package-path }}/package.json
      - name: Build
        run: npm run build --if-present --workspaces=true
      - id: pack-tarball
        name: Pack tarball
        run: |
          npm pack --pack-destination=$PWD --workspace=${{ inputs.package-name }}
          echo tarball-path=./${{ inputs.package-name }}-${{ steps.bump-version.outputs.version }}.tgz >> $GITHUB_OUTPUT
      - name: 'Sanity check: got tarball'
        run: compgen -G ${{ steps.pack-tarball.outputs.tarball-path }}
      - name: Upload tarball artifact
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: ${{ steps.pack-tarball.outputs.tarball-path }}

  bump-to-prepatch:
    name: Bump to prepatch
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: ${{ env.node-version }}
      - name: Bump to prepatch
        run: |
          npm version --no-git-tag-version --workspace=${{ inputs.package-name }} ${{ needs.build.outputs.version }}
          npm version --no-git-tag-version --workspace=${{ inputs.package-name }} prepatch
          cat ${{ needs.build.outputs.package-path }}/package.json
