name: Publish package to GitHub

on:
  workflow_dispatch: {}

env:
  node-version: lts/Hydrogen

jobs:
  prepare:
    name: Prepare tarballs
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ github.token }}
        name: Download release asset
        run: |
          gh release download release/vnext --repo ${{ github.repository }}
          ls -la

      - name: Add alias to */package.json
        run: |
          mkdir patched

          for TARBALL_NAME in `cat package-versions.json | jq -r 'to_entries | map(select(.value.private | not)) | map(.value.tarball) | join("\n")'`
          do
            tar -xvf $TARBALL_NAME
            cd package

            cat package.json | jq --argfile versions ../package-versions.json -r '. | (.name = "@compulim/" + .name) | (.dependencies |= (. | with_entries(if ({ (.key): {} } | inside($versions)) then . | (.value = "npm:@compulim/" + .key + "@" + .value) else . end))) | (.devDependencies |= (. | with_entries(if ({ (.key): {} } | inside($versions)) then . | (.value = "npm:@compulim/" + .key + "@" + .value) else . end)))' > package.tmp.json
            mv package.tmp.json package.json

            PATCHED_TARBALL_NAME=`npm pack --ignore-scripts --json | jq -r '.[0].filename'`
            mv $PATCHED_TARBALL_NAME ../patched/

            cd ..
            rm -r package
          done

      - name: List tarballs
        run: ls -l ./patched/*.tgz

      - uses: actions/upload-artifact@v3
        with:
          name: package-versions
          path: ./package-versions.json

      - uses: actions/upload-artifact@v3
        with:
          name: tarball
          path: ./patched/

  publish:
    environment:
      name: github-packages
    name: Publish
    needs:
      - prepare
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: package-versions

      - uses: actions/download-artifact@v3
        with:
          name: tarball

      - uses: actions/setup-node@v3
        with:
          node-version: lts/Hydrogen
          registry-url: https://npm.pkg.github.com/

      - name: List tarballs
        run: ls -l *.tgz

      - env:
          NODE_AUTH_TOKEN: ${{ github.token }}
        name: Publish release
        run: |
          for TARBALL_NAME in `ls -1 *.tgz`
          do
            # Make sure we don't publish tarball if it is already published.

            # PACKAGE_NAME_AND_VERSION=@someone/package-a@1.2.3
            PACKAGE_NAME_AND_VERSION=`tar -xf $TARBALL_NAME --to-stdout package/package.json | jq -r '.name + "@" + .version'`

            npm view $PACKAGE_NAME_AND_VERSION

            # If "npm view" failed, that probably means the package does not exists.
            if [ $? -ne 0 ]
            then
              npm publish $TARBALL_NAME
            fi
          done
