name: Publish package to GitHub

on:
  workflow_dispatch: {}

env:
  node-version: lts/Hydrogen

jobs:
  download-release:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ github.token }}
        name: Download release asset
        run: |
          gh release download release/vnext --repo ${{ github.repository }}
          ls -la

      - name: Add alias to */package.json
        run: |
          mkdir ./package/

          for TARBALL_NAME in `cat package-versions.json | jq -r 'to_entries | map(.value.tarball) | join("\n")'`
          do
            tar --to-stdout -xvf $TARBALL_NAME package/package.json | jq --argfile versions package-versions.json -r '. | (.name = "@compulim/" + .name) | (.dependencies |= (. | with_entries(if ({ (.key): {} } | inside($versions)) then . | (.value = "npm:@compulim/" + .key + "@" + .value) else . end))) | (.devDependencies |= (. | with_entries(if ({ (.key): {} } | inside($versions)) then . | (.value = "npm:@compulim/" + .key + "@" + .value) else . end)))' > package/package.json

            tar -uvf $TARBALL_NAME package/package.json

            cat package/package.json
            rm package/package.json
          done

      - uses: actions/upload-artifact@v3
        with:
          name: tarball
          path: '*.tgz'
