name: Test matrix

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

env:
  matrix1: '[{"name":"powerva-chat-adapter-test-util","path":"packages/powerva-chat-adapter-test-util","private":false,"version":"0.0.1-main.20230826-060844.5a47d26"},{"name":"powerva-turn-based-chat-adapter-framework","path":"packages/powerva-turn-based-chat-adapter-framework","private":false,"version":"0.0.1-main.20230826-060844.5a47d26"},{"name":"powerva-chat-adapter","path":"packages/powerva-chat-adapter","private":false,"version":"0.0.1-main.20230826-060844.5a47d26"},{"name":"pages","path":"packages/pages","private":true,"version":"0.0.0-main.20230826-060844.5a47d26"}]'
  matrix2: '[{"name":"package-a"},{"name":"package-b"}]'

jobs:
  prepare:
    name: Prepare
    outputs:
      matrix1: ${{ steps.write-outputs.outputs.matrix1 }}
      matrix2: ${{ steps.write-outputs.outputs.matrix2 }}
    runs-on: ubuntu-latest
    steps:
      - id: write-outputs
        name: Write to outputs
        run: |
          echo $matrix1 | jq -cr > /tmp/matrix1.json
          echo matrix1=$(< /tmp/matrix1.json) | tee --append $GIT_OUTPUT

          echo $matrix2 | jq -cr > /tmp/matrix2.json
          echo matrix2=$(< /tmp/matrix2.json) | tee --append $GIT_OUTPUT

  build1:
    name: Build 1
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(needs.prepare.outputs.matrix1) }}
        os:
          - ubuntu-latest
          - window-latest
    steps:
      - run: |
          echo ${{ matrix.name }} ${{ matrix.os }}
      - run: |
          echo << EOL
          ${{ toJSON(matrix) }}
          EOL

  build2:
    name: Build 2
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(needs.prepare.outputs.matrix2) }}
        os:
          - ubuntu-latest
          - window-latest
    steps:
      - run: |
          echo ${{ matrix.name }} ${{ matrix.os }}
      - run: |
          echo << EOL
          ${{ toJSON(matrix) }}
          EOL
