name: Test

on:
  workflow_dispatch: {}

jobs:
  prepare:
    outputs:
      matrix: ${{ steps.get-workspaces.outputs.workspaces }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: get-workspaces
        name: List workspaces
        run: |
          cat package.json | jq -r '.workspaces | join("\n")' | xargs --max-lines=1 --replace cat {}/package.json | jq .name > /tmp/workspaces.txt
          MATRIX=`jq -cn --slurpfile workspaces /tmp/workspaces.txt '{ name: $workspaces }'`
          echo workspaces=$MATRIX >> $GITHUB_OUTPUT

          echo \`\`\`json >> $GITHUB_STEP_SUMMARY
          echo $MATRIX >> $GITHUB_STEP_SUMMARY
          echo \`\`\` >> $GITHUB_STEP_SUMMARY

  build:
    needs:
      - prepare
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
      - run: echo ${{ matrix.name }}
