name: Test matrix

defaults:
  run:
    shell: bash


env:
  matrix1: '[{"name":"powerva-chat-adapter-test-util","path":"packages/powerva-chat-adapter-test-util","private":false,"version":"0.0.1-main.20230826-060844.5a47d26"},{"name":"powerva-turn-based-chat-adapter-framework","path":"packages/powerva-turn-based-chat-adapter-framework","private":false,"version":"0.0.1-main.20230826-060844.5a47d26"},{"name":"powerva-chat-adapter","path":"packages/powerva-chat-adapter","private":false,"version":"0.0.1-main.20230826-060844.5a47d26"},{"name":"pages","path":"packages/pages","private":true,"version":"0.0.0-main.20230826-060844.5a47d26"}]'
  matrix2: '[{"name":"package-a"},{"name":"package-b"}]'

jobs:
  build1:
    name: Build 1
    strategy:
      env:
      matrix:
        include: ${{ fromJSON(env.matrix1) }}
        os:
          - ubuntu-latest
          - window-latest
      steps:
        - run: |
            echo ${{ matrix.name }} ${{ matrix.os }}
        - run: |
            echo << EOL
            ${{ toJSON(matrix) }}
            EOL

  build2:
    name: Build 2
    strategy:
      env:
      matrix:
        include: ${{ fromJSON(env.matrix2) }}
        os:
          - ubuntu-latest
          - window-latest
      steps:
        - run: |
            echo ${{ matrix.name }} ${{ matrix.os }}
        - run: |
            echo << EOL
            ${{ toJSON(matrix) }}
            EOL
